### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by skdenmark** [akarnokd/RxAdvancedFlow#1]
Hi

You should consider publishing it as a NuGet package

Keep up the good work!

**Comment by akarnokd** [comment]
Hi, I thought about it but the code is only like 92% complete and I don't have unit tests either; I'm not into the C# ecosystem you see.

Btw, would you like to help with the unit tests or know somebody who is knowledgeable in C# ecosystem and would help out?

In addition, I managed to publish its dependency, ReactiveStreamsCS, via the NuGet gui app, but I have no idea how to add the ///<summary>

 documentation.

**Comment by akarnokd** [comment]
Done. https://www.nuget.org/packages/RxAdvancedFlow/
Let me know if it works.
